### ISSUE TITLE
miscellaneous problems

### ISSUE THREAD

**Issue by ZZ22upL** [ReCore-sys/ASMShare#4]
security issue - logs are publicly available
site runs significantly slower
interface is non-intuitive
long descriptions can cause issues when they collide with the short descriptions 
 
![Screenshot (37)](https://user-images.githubusercontent.com/66930027/123361201-c79dd400-d5ad-11eb-8486-7b1012a5069c.png)

**Comment by ReCore-sys** [comment]
Yeah I will need to fix logs, site speed is just a result of low cpu which might get fixed soon, interface is designed for people who are not idiots (so yeah will need some fixing) and the short descriptions now fade out when you hover, so no more collisions
